# Rust
[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  "}

[language-server.rust-analyzer.config]
cargo.features = "all"
rust-analyzer.check.command = "clippy"


# Java
[[language]]
name = "java"
scope = "source.java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", "build.gradle.kts"]
indent = { tab-width = 4, unit = "    " }

[language-server.jdlts]
command = "jdt-language-server"

formatter = { command = "google-java-format", args = ["-"] }

auto-format = true

